### PR TITLE
Receiver Email Added

### PR DESCRIPTION
**Pull request by Keshavjps28**
Hello Süleyman
I have added a functionality to allow the user to set recipient E-mail in case of E-mail share as discussed in this issue(https://github.com/yasirkula/UnityNativeShare/issues/79).
This is my first attempt at open source contribution hence would request you to guide me with the process.

### CODE REVIEW

**Comment by yasirkula** [comment]
Did you test the code yourself and verify that it works?

**Comment by Keshavjps28** [comment]
Yes

**Comment by yasirkula** [comment]
Sorry for the doubt but I'm sure that the following line will change the text instead of setting the recipient:

```java
if( recipients.length() > 0 )
	intent.putExtra( Intent.EXTRA_TEXT, recipients );
```

And there are numerous compilation errors in _NativeShare.cs_...

**Comment by Keshavjps28** [comment]
No, it is absolutely working fine in unity version 2019.2.17f1 and No error is occurring.

**Comment by yasirkula** [comment]
[Here's your NativeShare.cs file in full](https://github.com/Keshavjps28/UnityNativeShare/blob/60163d2d4160c708a054546fbde26b1c777277ae/Plugins/NativeShare/NativeShare.cs). This is probably not in sync with your own NativeShare file since there are compiler errors (undefined recipients variable, multiple SetTitle function declarations and etc.).

I am not planning to add recipients functionality at the moment but thanks for creating this pull request 🙂
